name: ammvee_release
description: "Asociacion de Mexicana de Medicos Veterinarios Especialistas en Equinos A.C"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  page_transition: ^2.0.9
  flutter_animated_button: ^2.0.0
  flutter_spinkit: ^5.1.0
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  animated_splash_screen:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
