import 'package:ammvee_release/addOns/isLoading.dart';
import 'package:ammvee_release/addOns/themeColors.dart';
import 'package:ammvee_release/logIn.dart';
import 'package:ammvee_release/medInfoCard.dart';
import 'package:flutter/material.dart';

class initialMenu extends StatefulWidget {
  const initialMenu({Key? key}) : super(key: key);

  @override
  State<initialMenu> createState() => _ChooseYourInstance();
}

class _ChooseYourInstance extends State<initialMenu> {
  bool loading = true;
  String dropdownvalue = 'Buscar Medicamento';
  List<String> medsArray = [
    "Aceite Mineral",
    "Acepromacina",
    "Acetato de metilprednisolona (intra-articular)",
    "Acetato de metilprednisolona (oftálmico)",
    "Acetazolamida",
    "Acetilcisteína (mucolítico)",
    "Acetilcisteína (lavado de bolsas guturales) ",
    "Acetilcisteína (oftálmica)",
    "Aciclovir",
    "Ácido Aminocapróico",
    "Ácido Ascórbico (Vitamina C)",
    "Ácido fólico",
    "Ácido Meclofenamico",
    "ACTH (Hormona Adrenocortocotropica)",
    "Ademetionina",
    "Albuterol (Salbutamol)",
    "Alopurinol",
    "Alprazolam",
    "Altrenogest",
    "Amikacina (intra-articular)",
    "Amikacina (Perfusión regional)",
    "Amikacina (reproducción) ",
    "Amikacina Sulfato",
    "Aminofilina",
    "Amoxicilina",
    "Ampicilina (para lavado intrauterino)",
    "Ampicilina sódica",
    "Anfotericina B",
    "Antitoxina tetánica",
    "Arginina (L)",
    "Arginina-Vasopresina (ADH)",
    "Arsénico sódico tiarsetasamida",
    "Aspirina (ácido acetilsalicílico)",
    "Atracurium besilate",
    "Atropina (oftálmica)",
    "Atropina (sulfato)",
    "Aurothioglucose (Tiomalato sódico de oro)",
    "Azatioprina",
    "Azitromicina",
    "Azosulfamida",
    "Azul de metileno",
    "Bacillus Calmette-Guerin (Vacuna)",
    "Bacitracina de Zinc",
    "Baclofeno",
    "Bario (sulfato)",
    "Benztropine Mesylate",
    "Bicarbonato de sodio",
    "Biosponge (Esmectita)",
    "Bismuto Subsalicilato",
    "Boldenona",
    "Borogluconato de Calcio",
    "Bretilio",
    "Bromhexina",
    "Bromuro de ipratropio",
    "Bromuro de Potasio",
    "Bromuro de Propanteline",
    "Butorfanol",
    "Cabergoline",
    "Cafeína",
    "Calcio EDTA",
    "Caolin pectina",
    "Carbamacepina",
    "Carbón activado",
    "Carprofeno",
    "Cefalexina",
    "Cefalotina",
    "Cefazolina",
    "Cefazolina (oftálmica)",
    "Cefazolina (reproducción)",
    "Cefepime",
    "Cefotaxima sódica",
    "Cefpodoxima proxetil",
    "Ceftazidima ",
    "Ceftiofur ",
    "Ceftiofur (intra-articular) sódico",
    "Ceftiofur (reproducción) sódico",
    "Ceftiofur acido libre cristalino",
    "Ceftriaxona ",
    "Ciclosporina A (oftálmico)",
    "Cimetidina",
    "Ciprofloxacina (oftálmica)",
    "Ciproheptadina",
    "Cisaprida",
    "Cisplatino",
    "Claritromicina ",
    "Clembuterol",
    "Clomipramina",
    "Cloprostenol sódico",
    "Cloranfenicol (oftálmico)",
    "Cloranfenicol Palmitato",
    "Cloranfenicol sodio succinato",
    "Cloruro de Calcio",
    "Cloruro de Potasio",
    "Colchicina",
    "Cromoglicato de sodio",
    "Dantroleno",
    "Dapsona",
    "Deslorelina Acetato",
    "Detomidina",
    "Dexametasona",
    "Dexametasona (oftálmica)",
    "Dextran 80",
    "Dextrosa 50%",
    "Diazepam",
    "Diazepam (reproducción)",
    "Diclofenaco (oftálmico)",
    "Dietilcarbamazina",
    "Difenhidramina",
    "Digoxina",
    "Dihidroestreptomicina",
    "Dimetil sulfoxido (DMSO)",
    "Dinoprost trometamina ",
    "Dioctisulfosucciniato (DSS) 5%",
    "Dipirona",
    "Diyodohidroxiquinoleina",
    "Dobutamina",
    "Domperidona",
    "Dopamina",
    "Doxapram",
    "Doxiciclina",
    "D-xilosa (glucosa)",
    "Efedrina (HCL)",
    "Enalapril",
    "Enrofloxacina",
    "Epinefrina",
    "Eritromicina esteareato",
    "Eritromicina etilsuccinato",
    "Eritropoyetina",
    "Estanozolol",
    "Estradiol 17 β",
    "Estradiol Cipionato",
    "Estreptomicina ",
    "Estrógenos conjugados",
    "Etodolaco",
    "Famotidin",
    "Fenbendazol",
    "Fenilbutazona",
    "Fenilefrina (HCL)",
    "Fenilpropanolamina",
    "Fenitoína liberación prolongada",
    "Fenobarbital",
    "Fenoxibenzamina",
    "Firocoxib",
    "Fluconazol",
    "Flufenazina",
    "Flunixin de meglumine",
    "Fluorouracilo (5-FU)",
    "Flurbiprofeno (oftálmico)",
    "Fluticasona",
    "Fosfato de Potasio",
    "Fosfato de Sodio",
    "Furosemida",
    "Gabapentina",
    "Gentamicina",
    "Gentamicina ( perfusiones regionales)",
    "Gentamicina (oftálmica)",
    "Gentamicina (reproducción)",
    "GNRH (Hormona Liberadora de Gonadotropina)",
    "Gonadotropina corionica",
    "Gonadotropina coriónica humana (HCG)",
    "Griseofulvina",
    "Guaifenesina",
    "Heparina",
    "Heparina de bajo peso molecular",
    "Hetastarch",
    "Hialuronato de sodio",
    "Hialuronato de sodio (intra-articular)",
    "Hidralazina (HCL)",
    "Hidrato de Cloral",
    "Hidroxizina (HCL)",
    "Ibuprofeno",
    "Imidocarb",
    "Imipenem-cilastatina",
    "Imipramina (HCL)",
    "Insulina Protamina Zinc",
    "Insulina R o N",
    "Interferón Alfa",
    "Interferón Alfa 2a recombinante",
    "Iohexol",
    "Isonazida",
    "Isoxuprina (HCL)",
    "Itraconazol",
    "Itraconazol 1% oftálmico",
    "Ivermectina",
    "Ketamina (analgesia)",
    "Ketamina (anestesia)",
    "Ketoconazol",
    "Ketoprofeno",
    "Lactasa",
    "Lactulosa",
    "Levamisol",
    "Levotiroxina",
    "Lidocaína",
    "Lidocaína (reproducción)",
    "Loperamida",
    "Lufenuron",
    "Magnesio, sulfato de (gastrointestinal)",
    "Maleato de Pirilamina",
    "Manitol",
    "Meclizina",
    "Meloxicam",
    "Meperidina",
    "Metformina",
    "Metionina",
    "Metocarbamol",
    "Metoclopramida",
    "Metrizamida",
    "Metronidazol",
    "Miconazol (oftálmico) 1%",
    "Miconazol tópico",
    "Midazolam",
    "Misoprostol",
    "Mitomicina oftálmica 0.4%",
    "Morfina",
    "Morfina (epidural)",
    "Moxidectina",
    "N- Butilescopolamina",
    "Naloxona",
    "Naproxeno",
    "Natamicina oftálmica",
    "Nedocromilo sódico",
    "Neostigmina",
    "Nitazoxanida",
    "Nitroglicerina tópica",
    "Norepinefrina",
    "Ofloxacina oftálmica",
    "Omeprazol",
    "Oxacilina",
    "Oxitetraciclina",
    "Oxitocina",
    "Pamoato Tartrato de Pirantel",
    "Pantoprazol ",
    "Penicilamina",
    "Penicilina G Potasica ",
    "Penicilina G procaínica ",
    "Penicilina Potasica V",
    "Pentobarbital sodico",
    "Pentoxifilina",
    "Pergolida",
    "Pilocarpina oftálmica",
    "Pirimetamina",
    "Piroxicam",
    "Plasma hiperinmune",
    "Polimixina B",
    "Ponazuril",
    "Prazicuantel",
    "Prednisolona",
    "Prednisolona Acetato de, 1% oftálmico",
    "Prednisolona Sódica Succionato",
    "Procainamida",
    "Progesterona y Estradiol 17 β",
    "Propanolol",
    "Propofol",
    "Psyllium Plantago (polvo)",
    "Quinapril",
    "Ranitidina",
    "Reserpina",
    "Reserpina (reproducción)",
    "Rifampicina",
    "Rimantadina",
    "Romifidina",
    "Rubeola (inmunomodulador)",
    "Salmeterol",
    "Selenio",
    "Sildenafil",
    "Solución Heparinizada",
    "Solución salina hipertónica 7%",
    "Succinato de Metilprednisolona",
    "Sucralfato",
    "Suero autólogo oftálmico",
    "Sulfadiazina sódica (oftálmica)",
    "Sulfadiazina/Trimetoprim",
    "Sulfametoxazol/trimetoprim ",
    "Sulfato de magnesio",
    "Sulfato de Neomicina",
    "Sulfato de Quinidina",
    "Sulfonato de poliestireno sódico",
    "Telitromicina",
    "Terbutalina",
    "Testosterona",
    "Tétanos (antitoxina) oftálmica",
    "Tetraciclina",
    "Tiamina (vitamina B1)",
    "Ticarciclina (reproducción)",
    "Ticarcilina",
    "Ticarcilina con ácido clavulánico",
    "Timolol (oftálmico)",
    "Tiroxina",
    "Tobramicina (oftálmica)",
    "Tolazolina",
    "Tramadol",
    "Triamcinolona Acetonida",
    "Triamcinolona Acetonida (intraarticular)",
    "Triamcinolona Acetonida (oftálmica)",
    "Trilostano",
    "Tripelenamina",
    "Ursodial",
    "Valaciclovir",
    "Vancomicina",
    "Vasopresina",
    "Vinagre",
    "Vincristina",
    "Vitamina B (complejo)",
    "Vitamina C",
    "Vitamina E",
    "Vitamina E/Selenio ",
    "Vitamina K1",
    "Voriconazol",
    "Xilacina",
    "Yodo povidona 2% oftalmica",
    "Yodo povidona solución 0.5% (reproduccion)",
    "Yoduro de Potasio",
    "Yoduro de Sodio",
    "Yohimbina"
  ];

  List<String> medsDose = [
    "PO: 7.5 ml/kg via SNG.\nPotros: 120 ml PO via SNG",
    "IV, IM, SC: 0.01-0.1 mg/kg\nOral: 0.1 - 0.2 mg/kg (efecto variable)",
    "100-120 mg por articulación.",
    "40 mg subconjuntival cada 1-3 semanas",
    "PO: 2.2 - 4.4 mg/kg  cada 12 hr. ",
    "IM, IV: 1.5 mg/kg cada 12 hr.\nPolvo oral: 0.1-0.3 mg/kg al día por 5 días o más",
    "20-60 ml acetil cisteína 20%",
    "0.2 ml solución tópica 5% cada 1-4 hr.\n5% acetilcisteína 2-6 gotas cada 2 hr. para úlceras o cada 6 hr. para síndrome de ojo seco",
    "PO: 20 mg/kg cada 8 hr.\nIV: 10 mg/kg cada 12 hr.\nTópica (pomada oftálmica) para queratitis aplicar cada 3-4 hr.",
    "20-40 mg/kg diluido en 1-3 L de SSF IV lento, administrar de 30-60 min.",
    "PO: 0.5-2 gr/kg cada 12-24 hr.\nPotros: 10-100 mg/kg/día PO o IV diluido en fluidos cada 24 hr. ",
    "400-500 mg/día",
    "PO: 2.2 mg/kg cada 24 hr.",
    "IM: 100-250 µg dosis única total para un potro de 50 kg. ",
    "PO: 20 mg/kg cada 24 hr. ",
    "1-2 µg/kg inhalado cada 12 hr. ",
    "PO: 44 mg/kg en las primeras 4 horas de vida.",
    "PO: 0.035 mg/kg cada 8-12 hr. ",
    "PO: 0.044 mg/kg cursos de 15 días o más para suprimir o regular el estro. ",
    "500 mg por articulación cada 24- 48 hr.\n250-750 mg/articulación.",
    "Adultos: 2-5 mg/kg \nPotros perfusión regional: 1-2 gr con 20-60 ml de Solución Salina Fisiológica cada 24-48 hr.",
    "20-40 mg/kg diluido en 1-3 L de SSF IV lento, administrar de 30-60 min.",
    "Adultos: 10-15 mg/kg cada 24 hr. IV lento o IM. \nPotros: 20-25 mg/kg cada 24hrs. IV lento o IM.",
    "5-10 mg/kg en 100 ml de SSF IV (lenta) administrar de 30-60 min. \nIV: 2-5 mg/kg, lenta cada 8-12 hr.\nPO: 5-10 mg/kg cada 12 hr.",
    "PO: 30-50 mg/kg cada 8-12 hr. \nPotros: 10-30 mg/kg IM/PO cada 12 hr.",
    "3 grs. en 60 ml de solución salina estéril cada 24 hr. Por 3 días.",
    "IV, IM: 20 mg/kg cada 6-8 hr.",
    "Dosis de prueba: IV 100 mg (totales).\nDosis inicial: 0.2 mg/kg aumentando a 0.5-1.0 mg/kg después de 2 días.\nPreparación: 0.1 mg/ml diluido en un litro de dextrosa al 5%.\n Administrar en 60 min cada 48 hr por 28 días.",
    "Adulto: IV o IM 5,000-50,000 UI (diluido si es IV)\nPotros: SC 2,500-3,500 UI.",
    "Solución al 10% (100 grs. En un L de solución salina) IV cada 12 hr. De 1-3 días.",
    "0.25-05 Mg/kg/min IV Infusión continua\n40-60 UI SC o IM\n0.4-0.6 U/kg IV\n.002-.007 units/kg/min",
    "IV: 0.1 mg/kg/día.",
    "PO: 10-100 mg/kg cada 8-24 hr.\nAntitrombótico: 4-12 mg/kg.\nTópico: máximo 50 g gel cada 24 hr.",
    "IV: 0.2mg- 0.28/kg.\nDosis inicial: 0.1-0.25 mg/kg IV.\nDosis siguientes: ¼- ½ de la dosis inicial IV.",
    "Tópico: 0.2 ml cada 2-48 hr. Para dilatación de pupila",
    "a)	IV ó IM: 0.015-0.02 mg/kg.\nb) 5-10 mg por articulación.\nc) IV, IM, SC: 0.02-0.10 mg/kg.\nd) IV: 5 mg.\ne)	1 mg/kg cada 2-6 hr.",
    "IM: 50 mg Dosis inicial, seguido de 1 mg/kg IM cada 7 días, después cada 14 días y luego cada 28 días.",
    "PO: 1-2mg/kg cada 24 hr.",
    "PO: 10 mg/kg cada 24 hr. por 5 días y luego cada 48 hr.",
    "IV: 2 mg/kg.",
    "IV: 0.5-2 mg/kg",
    "0.3-0.5 ml por cm3 cada 14 días de 3 a 5 aplicaciones.",
    "Tópico (pomada): Aplicar cada 8 hr.",
    "PO: 0.4 mg/kg cada 8 hr.",
    "PO: 3 gr/kg dosis única.",
    "a) PO: 0.4 mg/kg cada 8 hr. \nb) IV: 8 mg/500kg lento",
    "PO: 30-150 gr/día \nIV: mEq=25 – valor bicarbonato x 0.6 (potro) ó 0.3 (adulto) x peso vivo (kg) al 5% infusión IV 1 mEq/kg, lento. ",
    "Potros: 1 gr/kg cada 4 hr. \nPO Adultos: 1 gr/kg cada 6-12 hr. Vía SNG.",
    "Potros: 0.5-1 ml/kg PO cada 6-12 hr. \nAdultos: 1 ml/kg vía SNG cada 6 hr.",
    "IM: 1.1 mg/kg tratamiento en intervalos de cada 3 semanas.",
    "Adicionar 20ml a cada litro de fluidos.",
    "IV: 3-5 mg/kg en bolo.",
    "PO: 0.2-0.4 mg/kg una vez al día. \nIV: 0.2-0.4 mg/kg una vez al día.",
    "5 activaciones (90 µg por activación) nebulizador 250-500 µg/1-2mL",
    "PO: 25-30 mg/kg cada 12 hr.",
    "IV: 30 mg/kg ",
    "a)	IV, IM: 0.01-0.1 mg/kg \nb)	IV: 0.01-0.015 mg/kg/hr. en infusión continua después de un bolo de 0.02 mg/kg bolo IV. \vIV, IM, SC: 0.05-0.2 mg/kg (dosis más bajas se utilizan combinadas con agonistas α2 para sedación. \vPotros: 0.05 mg/kg IV, SC, IM.",
    "PO: 2-3 mg/500kg cada 12-24 hr.",
    "Dosis inicial de 10 mg/kg PO y mantenimiento 2.5 mg/kg PO cada 12 hr.",
    "Solución al 6.6%: 25 mg/kg IV en dextrosa al 5% lentamente cada 8 hr por 4 días.",
    "PO: 2-4 L/500kg cada 12 hr. \nPotros: 80-100 ml PO cada 8 hr.",
    "PO: 4-8 mg/kg cada 8 hr.",
    "PO: 1-3 gr/kg cada 8 hr.",
    "IV: 0.7 mg/kg cada 24 hr. \nPO: 1 mg/kg cada 24 hr."
    "PO: 25-30 mg/kg cada 6-8 hr.",
    "Potros: 18 mg/kg IV, IM cada 8 hr. \nAdultos: 20 mg/kg IV, IM cada 6 hr.",
    "IV, IM: 11-20 mg/kg cada 6-8 hr.",
    "Tópico: 0.2 ml cada 8 hr.",
    "1 gr en 60 ml de SSF para lavados IU. cada 24 hr. De 1-5 días.",
    "Potros: 11 mg/kg IV cada 8 hr. \nAdultos: 2.2 mg/kg IV cada 8 hr.",
    "Potros: 20-40 mg/kg IV cada 6-8 hr. \nAdultos: 15-25 mg/kg IV,IM cada 8-12 hr.",
    "PO: 10 mg/kg cada 6-8 hr.",
    "Potros: 20 mg/kg IV, IM. \nAdultos: 25-50 mg/kg IV cada 6-8-12 hr.",
    "Potros: 5-10 mg/kg IV, IM ó SC cada 6 hr. \nAdultos: 2.2 mg/kg IM, IV ó SC cada 12 hr.",
    "150 mg por articulación cada 24 hr.",
    "1 gr en 60 ml de SSF lavados IU cada 24 hr. De 3-5 días",
    "Potros: 13.2 mg/kg. \nAdulto: 6.6 mg/kg IM.",
    "IV, IM: 25-50 mg/kg cada 12 hr.",
    "0.2 ml cada 8 hr.",
    "a)	20-25 mg/kg PO ó 6.6 mg/kg IV cada 8 hr. \nb)	2.5 mg/kg PO cada 12 hr.",
    "Tópica: 0.2 ml cada 8 hr.",
    "PO: 60 mg/450kg  cada 12-24 hr.",
    "PO: 0.1-0.8 mg/kg cada 8 hr.",
    "1 mg por cm3 intratumoral.",
    "PO: 7.5 mg/kg cada 12 hr. \nAdicionarle rifampicina \nNo usar en adultos",
    "PO: 0.8-3 µg/kg cada 12 hr.",
    "IV: 2.2 mg/kg",
    "IM: 250 µg cada 24 hr.",
    "Tópico: 0.2 ml cada 8 hr.",
    "Potros: 50 mg/kg PO (día 1-2: cada 12 hr) (día 3-7: cada 8 hr) (día 7 o más: cada 6 hr). \nAdultos: PO 45-50 mg/kg cada 8 hr.",
    "Adultos: IV, IM 25 mg/kg cada 6-12 hr. \nPotros: 25 mg/kg IV cada 6 hr. ",
    "IV: 3-5 mg/kg lentamente ",
    "IV: 20-40 mEq/L",
    "PO: 1 mg/100kg cada 12-24 hr.",
    "80 mg/kg cada 24 hr.",
    "Preventivo: 2-4 mg/kg PO cada 24 hr. \nTerapéutico: 2.5 mg/kg IV en SSF.",
    "PO: 3 mg/kg cada 24 hr. de 45 a 50 días.",
    "IM: 1.5 mg/500kg \nImplante de 2.1 mg cada ciclo estral, 24 horas antes de la copula.",
    "IV, IM: 0.005-0.02 mg/kg potros y adultos.",
    "PO, IV, IM: 0.02-0.2 mg/kg cada 24 hr.",
    "Tópica: 0.2 ml cada 4-12 hr.",
    "IV: 8 gr/kg cada 24 hr lento por 3 días.",
    "500 ml en 5 litros de Ringer Lactato = solución 5%. \nPotros: 4-8 mg/kg/min IV."
    "Potros: 5-15 mg IV, IM. \nAdultos: 15-30 mg IV."
    "Sementales: 10-20 mg IV 5-7 minutos previos a la copula.",
    "Tópico: 0.2 ml cada 8 hr.",
    "PO: 3 mg/kg cada 24 hr.",
    "IV: 0.6 mg/kg cada 24-48 hr. \nPO: 0.5-1 mg/kg",
    "PO: 0.1-0.3 mg/kg cada 12 hr.",
    "IV: 25 mg/kg cada 24 hr.",
    "IV: 0.5-1 ml/kg cada 24 hr. Diluido en SSF. \nPotros: 0.5 ml/kg IV cada 24 hr. Diluido en SSF.",
    "IM: 1 mg/45.4kg dosis única.",
    "10-20 mg/kg en 4-8 L por SNG dosis única.",
    "IV, IM: 22 mg/kg",
    "PO: 10 gr/450kg cada 24 hr.",
    "1-5 µg/kg/min una gota por segundo en un caballo de 500kg. \nPotros: 2-10 µg/kg/min infusión continua IV.",
    "PO: 1.1 mg/kg cada 24 hr por 10-20 días. Por 10 días previos al parto, continuar por 5 días más si la cantidad de leche no es adecuada.",
    "200 mg en 500 ml de dextrosa al 5% administrar: 2-5 µg/kg/min (0.45ml/kg/hr.).",
    "Adultos: 0.5-1 mg/kg IV. \nNeonatos: 0.5-1 mg/kg IV, SC, IM. \nSublingual: 40-100 mg/kg ",
    "PO: 10 mg/kg cada 12 hr.",
    "0.5 g/kg en una solución al 10% vía SNG, colectar muestra sanguínea a las (0, 30, 60, 90, 120, 150, 180, 210, 240 minutos) posteriores a la administración",
    "0.03-0.2 mg/kg IV en 1 L de SSF en 30 min.",
    "PO: 0.5-1 mg/kg cada 24 hr.",
    "Adultos: 7.5 mg/kg PO cada 24 hr.",
    "IV: 0.01-0.02 mg/kg \nIV, IC: 0.1-0.2 mL/50kg \nAnafilaxis: 0.2-0.4 mL/50kg IM, SC.",
    "PO: 15-25 mg/kg cada 6-8 hr. \nPotros: 25 mg/kg PO cada 8hr.",
    "PO: 25 mg/kg cada 8 hr.",
    "SC: 50 UI/kg una vez por semana.",
    "IM: 0.55 mg/kg  profunda",
    "IM: 30 mg/kg  dosis única.",
    "IM: 8 mg/500kg dosis única.",
    "IM: 11 mg/kg cada 12 hr.",
    "IV: 20-50 mg/500 kg.",
    "PO: 23 mg/kg cada 24 hr.",
    "PO: 3 mg/kg cada 12 hr.",
    "PO: 10 mg/kg cada 24 hr. por 5 dias.",
    "PO, IV: 2.2-4.4 mg/kg cada 12 hr. \nPotros: 2.2mg/kg IV, PO cada 12-24 hr.",
    "20-80 µg/kg IV en 500 ml de SSF en 15 min (nefroesplénico). \n20 mg dosis total (para fimosis). \nPotros: 0.2-1 µg/kg/hr.",
    "PO: 1-2.5 mg/kg cada 8-12 hr.",
    "Potro: 2.8-16.5 mg/kg PO cada 8 hr. \nAdulto: 10 mg/kg PO cada 12 hr.",
    "PO: 2-12 mg/kg cada 12-24 hr. \nAdultos: 12-20 mg/kg IV diluido en 30 mL de SSF durante 30 min dosis inicial, seguido de 1-9 mg/kg para mantenimiento. \nPotros (convulsión): 5-20 mg/kg IV diluido en 30 mL de SSF durante 30 min",
    "PO: 0.2-0.6 mg/kg cada 24 hr.",
    "PO: 0.1 mg/kg cada 24 hr. ",
    "Dosis inicial: 14 mg/kg seguida por 5 mg /kg PO cada 12-24 hr.",
    "IM: 0.05-0.1 mg/kg cada 21-28 días ",
    "Adultos: 0.5-1.1 mg/kg IV, PO cada 12 hr. \nPotros: 0.5-1.1 mg/kg IV cada 12 hr.",
    "Machos: aplicar tópico cada 14 días 2-5 tratamientos \nHembras. Aplicar tópico diario de 1 a 4 meses",
    "Tópico: 0.2 mL cada 8-12 hr.",
    "1000-2500 µg/caballo cada 12-24 hr.",
    "IV: 4-10 gr (450 kg) diluidos en SSF cada 24 hr.",
    "4-10 gr diluidos en SSF cada 24 hr. (450 kg).",
    "IV: 0.5-2 mg/kg cada 12-24 hr.",
    "PO: 2.5-10 mg/kg cada 8 hr.",
    "Adultos: 6.6 mg/kg IV cada 24 hr. \nPotros menores de 14 días: 12 mg/kg IV cada 36 hr.",
    "Perfusión: 1/3 de la dosis calculada por peso cada 24 hr. Diluida en cloruro de sodio al 0.9%.",
    "Tópico: 0.2 ml tópicos cada 12-24 hr.",
    "2 gr en 60 ml de solución salina. \nAl 8.4% de bicarbonato de sodio cada 24 hr. por 3-5 días.",
    "a)	IV, IM: 40-100 µg 4-12 hr. \nb) SC (criptoorquídeos): 500 mg/kg cada 12 hr. por 10 días.",
    "IM, SC: 2,500-4,000UI.",
    "IM, SC: 2,500-4,000 UI.",
    "PO: 5-10 mg/kg cada 24 hr. de 7 a 28 días.",
    "IV: 20-120 mg/kg (inducción). \nIV: 20-50 mg/kg combinado con α2 agonista.",
    "SC, IV: 40-80 UI/kg cada 8 hr.",
    "Potros: 100 UI/kg SC cada 24 hr. \nEnoxheparina: 40-80 UI/kg SC cada 24 hr. \n1,000 UI =10 mg.",
    "IV: 10 ml/kg se puede repetir en 24-36 hr.",
    "IV: 40 mg una vez por semana.",
    "IA: 20 mg.",
    "PO: 0.5-1.5 mg/kg cada 12 hr.",
    "PO: 3-6 gr/45kg diluido en agua.",
    "PO: 0.5-1.5 mg/kg cada 8 hr.",
    "PO: 25 mg/kg cada 8-12 hr. Por 6 días.",
    "IM: 4 mg/kg cada 72 hr por 4 tratamientos.",
    "IV: 10 mg/kg diluido en SSF en 20 min cada 8 hr.",
    "PO: 2 mg/kg.",
    "IM o SC: 0.4 UI/kg cada 24 hr.",
    "SC ó IV: 0.1-0.2 UI/kg.",
    "Humano: PO 50 UI cada 24 hr. Por 5 días. \nRecombinante: PO 90 UI cada 24 hr. Por 5 días.",
    "IV: 3,000,000 unidades en 1 L de SSF cada 24 hr. Por 3 días.",
    "50 ml en el espacio subaracnoideo (remplazar por misma cantidad de líquido cefalorraquídeo).",
    "PO: 10-20 mg/kg cada 12-24 hr.",
    "PO: 0.6 mg/kg cada 12 hr.",
    "PO: 6 mg/kg cada 24 hr. \nTópico: 1% en 30% DMSO.",
    "Tópica: 0.2 ml cada 8-12 hr.",
    "PO: 200 µg/kg",
    "IV: 0.4-0.8 mg/kg/hr. Infusión",
    "Inducción: IV 2.2 mg/kg. \nMantenimiento: 5-20 µg/kg/min. \nPotros: IV 2 mg/kg.",
    "PO: 10 mg/kg cada 24 hr.",
    "IV: 2.2 mg/kg cada 24 hr.",
    "PO: 6,000-9,000 Unidades/50kg cada 3-8 hr.",
    "PO o vía rectal: 150-200 ml 6-12 hr.",
    "PO: 2-3 mg/kg cada 24 hr. De 3 a 5 días.",
    "a)	PO: 0.5-3 mg/45kg 24 hr. \nb)	PO: 2-4 veces dosis para hipotiroidismo 12-24 hr.",
    "a)	IV: 0.5-1 mg/kg cada 5 min. \nb) 1.3 mg/kg en bolo, dosis única. Infusión continua 0.03-0.05 mg/kg/min.",
    "6 mL/400kg.",
    "PO: 0.1-0.2 mg/kg cada 6 hr.",
    "PO: 5 mg/kg cada 24 hr.",
    "1 gr/kg vía sonda con 4-8 L agua cada 12-24 hr.",
    "IM, SC o IV lento: 1 mg/kg.",
    "IV 500 mg-1gr/kg lento, cada 12 hr. diluido en una solución 20% administrar en 30 min.",
    "PO: 25-50 mg para 75 kg cada 12 hr. \nPotros: 0.25-1 gr/kg IV en 30 min cada 12 hr.",
    "Potros: 0.6 mg/kg PO cada 12 hr.",
    "IM o IV: 0.5 mg/kg cada 4 hr.",
    "PO: 30-50 mg/kg cada 8-12 hr.",
    "PO: 30-60 gr cada 24 hr.",
    "IV: 5-25 mg/kg lento cada 12 hr. \nPO: 25-50 mg/kg cada 12 hr.",
    "IV o IM: 0.1-0.2 mg/kg cada 6-12 hr. \nIV: 0.04 mg/kg/hr infusion continua.",
    "IV: 9.33 gr en 21 mL de SSF para 250 kg.",
    "PO: Adultos 10-15 mg/kg cada 6-8 hr. \nRectal: 50 mg/kg cada 12 hr. \nPotros: 10-15 mg/kg PO cada 8-12 hr.",
    "Tópico: 0.2 ml cada 4-12 hr.",
    "Shampoo de uso diario.",
    "IM o IV: 0.06-0.1 mg/kg.",
    "PO: 1.5-5 µg/kg cada 12 hr.",
    "Tópico: 2 gotas cada 8 hr.",
    "IV o IM: 0.1 mg/kg cada 4-12 hr.",
    "0.1 mg/kg.",
    "PO: 0.4 mg/kg.",
    "IV o IM: 0.3 mg/kg.",
    "a) Potros: IV 4 mg. \nb) IV: 12-20 mg en bolo",
    "PO: 10 mg/kg cada 12-24 hr.",
    "Tópica: 0.2 ml cada 4-12 hr.",
    "Nebulización: 17.5mg cada 12-24 hr.",
    "SC: 0.011-0.033 mg/kg cada 4 hr.",
    "PO: 25 mg/kg cada 24 hr. Por 5 días \nPO: 50 mg/kg cada 24 hr. Por 23 días \nPara Rotavirus: 25 mg/kg PO cada 24 hr. Por 7 días ",
    "Tópico: 15 mg cada 24 hr.",
    "IV: 0.2-2 µg/kg/min.",
    "Tópica: 0.2 ml cada 2-12 hr.",
    "PO: 4 mg/kg cada 24 hr. \nIV: 1.5 mg/kg cada 24 hr.",
    "IV o IM: 20 mg/kg cada 6-8 hr.",
    "A)	IV: 2.5-3 gr en 1 L. De SSF cada 24 hr. \nIV: 6.6 mg/kg lento cada 12-24 hr.",
    "IM: 40-60 UI \na)	IV: 0.11-0.22 UI/kg. \nb)	IM: 20-30 UI cada 60-90 min. c)	\nIM: 10-20 UI 4-8 hr. Después de la monta.",
    "PO: 6.6 mg/kg",
    "IV: 1.5 mg/kg cada 24 hr.",
    "PO: 3 mg/kg cada 6 hr.",
    "IV: 22,000-50,000 UI/kg cada 6 hr.",
    "IM: 20,000-40,000 UI/kg cada 12 hr. \nPotros: IM 22,000 UI.",
    "PO: 40,000-100,000 UI/kg cada 8-12 hr. ",
    "IV: 2-10 mg/kg. ",
    "PO: 7.5 mg/kg cada 8-12 hr.",
    "PO: 0.002-0.006 mg/kg cada 24 hr.",
    "Tópico: 2% cada 6 hr.",
    "PO: 1 mg/kg cada 24 hr.",
    "PO: 0.2 mg/kg cada 24 hr.",
    "a)	IV: 20 ml/kg \nb)	IV: 2-4 ml/kg \nc) IV: 10 ml/kg",
    "IV: 6,000 UI/kg cada 8-12 hr.",
    "PO: 5-10 mg/kg cada 24 hr. Por 28 días.",
    "PO: 1-1.5 mg/kg",
    "PO: 1 mg/kg cada 24 hr.",
    "Tópico: 0.2ml cada 4-12 hr.",
    "IV o IM: 1-5 mg/kg cada 12-24 hr. \nPotros: IV 2 mg/kg cada 24 hr.",
    "IV: 1 mg/kg/min (20 mg/kg en 250ml SSF) administrar en 20-30 min",
    "IM: 150 mg + 10 mg cada 24 hr.",
    "IV: 0.03 mg/kg \nPO: 0.38-0.78 mg/kg cada 8 hr.",
    "Inducción: IV 2.4 mg/kg a efecto. \nMantenimiento: 0.3 mg/kg/min \nPotros: IV 2 mg/kg",
    "PO: 1 g/kg vía sonda cada 12-24 hr.",
    "PO: 120-140 mg cada 12-24 hr. para (500-700kg).",
    "PO: 6.6 mg/kg cada 6-8 hr. \nIV: 1.4-2 mg/kg cada 6-8 hr.",
    "PO: 2.5 mg/kg cada 24 hr.",
    "PO: 2.5 mg/450kg cada 24 hr. Por 7-10 días.",
    "Potros: PO 5 mg/kg cada 12 hr.",
    "IV: 5 mg/kg cada 4 hr. (durante brote). \nPO: 30/mg/kg cada 12 hr. por 7-10 días.",
    "Analgesia/Sedación: 40-120 µg/kg IV \nPre-anestesico: IV 0.075 mg/kg.",
    "SC: 2 ml (cuello) cada 24 hr. Por 3-6 días.",
    "Nebulización: 0.4 µg/kg (dos inhalaciones).",
    "IM: 0.06 mg/kg (día 3-8-10).",
    "PO: 0.5-2.5 mg/kg cada 24 hr.",
    "10,000 UI por L de SSF.",
    "IV: 2-5 ml/kg en bolo por 10-15 min.",
    "IV: 1 mg/kg diluido en SSF.",
    "Adultos: PO 20 mg/kg cada 8 hr. \nPotros: PO 20 mg/kg cada 6 hr.",
    "Tópico: 0.2 ml cada 1-4 hr.",
    "Tópico: 0.2 ml cada 4-12 hr. O mezclar 1 ml crema en 8 ml de lagrima artificial.",
    "PO: 24 mg/kg cada 12 hr.",
    "Potros: PO 20-30 mg/kg cada 12 hr.",
    "Potros: IV 20 mg/kg diluido lentamente cada 12-24 hr. \nAdultos: 25-50 mg/500kg IV diluido en 1 L. De suero, administrar 30 min.",
    "PO: 5-15 mg/kg cada 24 hr.",
    "PO: 22 mg/kg via sonda cada 2 hr por 4-5 tratamientos.",
    "Potros: PO 15-30 gr/100kg o enema cada 12 hr.",
    "PO: 15 mg/kg cada 12-24 hr.",
    "PO: 0.06 mg/kg cada 8-12 hr. \nPotros: PO 10-15 mg cada 8-12 hr. \nAdultos: PO 30 mg cada 8-12 hr.",
    "SC: 0.1-0.2 mg/kg cada 48 hr. Por 14 días.",
    "Subconjuntival: 1,000 UI cada 24 hr.",
    "IV: 6.6 mg/kg cada 12-24 hr.",
    "IM, SC o IV: 1 mg/kg cada 24 hr.",
    "Intrauterino: 3-6 gr diluido en 60 ml de agua esteril.",
    "IV: 50 mg/kg cada 8 hr.",
    "IV: 50-60 mg/kg cada 6-8 hr.",
    "Tópico: 1-5 gotas 5% cada 12 hr.",
    "PO: 0.01 mg/kg cada 24 hr.",
    "Tópico: 0.2 ml cada 12 hr.",
    "IV: 2-4 mg/kg ",
    "PO: 5-10 mg/kg cada 12 hr.",
    "IM: 0.02 mg/kg.",
    "Intraarticular: 6 mg.",
    "Subconjuntivales: 6 mg cada 1-3 semanas",
    "PO: 1 mg/kg cada 24 hr.",
    "IM o IV: 1 mg/kg cada 6-8 hr.",
    "PO: 10 mg/kg cada 12 hr.",
    "PO: 27 mg/kg cada 8 hr por dos días, bajar a 18 mg/kg cada 12 hr por 7-14 días.",
    "IV: 7.5 mg/kg cada 8 hr. diliudo en 1 L de SSF pasar en 30-45min. \nPotros: PO 4 mg/kg dosis inicial, seguido de 2 mg/kg cada 6 hr.",
    "IV: 0.4-0.6 UI/kg.",
    "PO: 250 ml cada 24 hr. (500kg).",
    "IV: 0.004 mg/kg de una vez al día, a dos veces por semana (2 mg totales 500 kg).",
    "IM: 1 ml/50kg o en fluidos.",
    "IV: 10-30 mg/kg en SSF cada 24 hr. \nPO: 10-20 gr cada 24 hr."
    "PO: 20 UI/kg cada 24 hr.",
    "Potros: IV 0.06 mg/kg lento o IM profundo.",
    "SC: 300-500 mg cada 24 hr. (Adulto).",
    "PO: 4 mg/kg cada 12 hr.",
    "Sedación: IV 0.2-1 mg/kg \nPreanestésico: IV 1 mg/kg.",
    "Tópico: 0.2 ml cada 24 hr.",
    "2 a 4 litros de agua con yodo al 10% cada 24 hr. Por 1-7 días.",
    "PO: 2 mg/kg cada 24 hr.",
    "IV: 20 mg/kg cada 24 hr.",
    "IV: 0.075-0.12 mg/kg \nPotros: IV 0.1 mg/kg"
  ];

  bool virgin = true;
  List<String> filteredList = [];
  late String medName;

  @override
  void initState() {
    super.initState();
    //TODO: "GET" FROM DB INFORMATION OF MEDICINE NAMES
    setState(() {
      filteredList.addAll(medsArray);
      loading = false;
    });
  }

  @override
  Widget build(BuildContext context) => loading
      ? const isLoading()
      : PopScope(
          canPop: false,
          child: Scaffold(
            appBar: AppBar(
              backgroundColor: Colors.white,
              elevation: 1,
              leading: IconButton(
                icon: const Icon(Icons.power_settings_new_sharp),
                color: Colors.black,
                onPressed: () {
                  showAlertDialog(context);
                },
              ),
              centerTitle: true,
              title: Row(
                crossAxisAlignment: CrossAxisAlignment.center,
                mainAxisAlignment: MainAxisAlignment.center,
                children: [
                  Image.asset('assets/logo.png',
                      height: MediaQuery.of(context).size.height * 0.03),
                ],
              ),
              actions: <Widget>[
                Opacity(
                  opacity: 0,
                  child: IconButton(
                    onPressed: () {},
                    icon:
                        const Icon(Icons.people_alt_sharp, color: Colors.white),
                  ),
                )
              ],
            ),
            backgroundColor: kWhite,
            body: SafeArea(
              child: Container(
                height: MediaQuery.of(context).size.height,
                width: double.infinity,
                child: SingleChildScrollView(
                  child: Column(
                    crossAxisAlignment: CrossAxisAlignment.center,
                    mainAxisAlignment: MainAxisAlignment.center,
                    children: <Widget>[
                      RawAutocomplete(
                        optionsBuilder: (TextEditingValue textEditingValue) {
                          if (textEditingValue.text == '') {
                            filteredList.clear();
                            filteredList.addAll(medsArray);
                            return const Iterable<String>.empty();
                          } else {
                            List<String> matches = <String>[];
                            filteredList.clear();
                            virgin = false;
                            matches.addAll(medsArray);
                            matches.retainWhere((s) {
                              return s.toLowerCase().contains(
                                  textEditingValue.text.toLowerCase());
                            });
                            print("Matches from search: $matches");
                            print("Text ${textEditingValue.text}");
                            filteredList.addAll(matches);
                            return matches;
                          }
                        },
                        onSelected: (String selection) {
                          print("Sospechoso numero 1 $selection");
                          medName = selection;
                          setState(() {
                            filteredList.clear();
                            filteredList.add(medName);
                          });
                        },
                        fieldViewBuilder: (BuildContext context,
                            TextEditingController textEditingController,
                            FocusNode focusNode,
                            VoidCallback onFieldSubmitted) {
                          return Container(
                            margin: const EdgeInsets.all(20),
                            padding: const EdgeInsets.symmetric(
                                horizontal: 25, vertical: 5),
                            decoration: BoxDecoration(
                              borderRadius: BorderRadius.circular(50),
                              border: Border.all(color: kBlack),
                            ),
                            child: TextField(
                              decoration: const InputDecoration(
                                  border: InputBorder.none,
                                  icon: Icon(Icons.search, color: kBlue),
                                  hintText: "Buscar Medicamento"),
                              controller: textEditingController,
                              focusNode: focusNode,
                              onChanged: (String value) {
                                setState(() {
                                  medName = value;
                                  print("Sospechoso numero 2 $value");
                                });
                              },
                            ),
                          );
                        },
                        optionsViewBuilder: (BuildContext context,
                            void Function(String) onSelected,
                            Iterable<String> options) {
                          return Material(
                              child: SizedBox(
                                  height: 200,
                                  child: SingleChildScrollView(
                                      child: Column(
                                    children: options.map((opt) {
                                      return InkWell(
                                          onTap: () {
                                            onSelected(opt);
                                          },
                                          child: Container(
                                              padding:
                                                  const EdgeInsets.symmetric(
                                                      horizontal: 30),
                                              color: Colors.black,
                                              child: Container(
                                                width: double.infinity,
                                                padding:
                                                    const EdgeInsets.all(10),
                                                child: Text(opt),
                                              )));
                                    }).toList(),
                                  ))));
                        },
                      ),
                      LayoutBuilder(builder: (context, constraints) {
                        if (filteredList.isEmpty && !virgin) {
                          return const Text("No se encontro ningun medicamento",
                              style:
                                  TextStyle(color: Colors.grey, fontSize: 20));
                        } else {
                          return SingleChildScrollView(
                            child: GridView.count(
                              physics: const BouncingScrollPhysics(),
                              scrollDirection: Axis.vertical,
                              shrinkWrap: true,
                              childAspectRatio: 10 / 2.5,
                              crossAxisCount: 1,
                              children:
                                  List.generate(filteredList.length, (index) {
                                return Card(
                                  color: kWhite,
                                  elevation: 5,
                                  margin: const EdgeInsets.symmetric(
                                      vertical: 10, horizontal: 10),
                                  child: Center(
                                    child: Column(
                                      mainAxisSize: MainAxisSize.min,
                                      children: <Widget>[
                                        ListTile(
                                          leading: const ImageIcon(
                                            AssetImage("assets/jeringa.png"),
                                            color: Color(0xFF030303),
                                          ),
                                          title: Text(
                                            filteredList[index],
                                            style: const TextStyle(
                                                fontSize: 15, color: kBlack),
                                          ),
                                          onTap: () {
                                            Navigator.push(
                                              context,
                                              MaterialPageRoute(
                                                builder: (context) {
                                                  return medInfoCard(
                                                      medName:
                                                          filteredList[index]);
                                                },
                                              ),
                                            );
                                          },
                                        ),
                                      ],
                                    ),
                                  ),
                                );
                              }),
                            ),
                          );
                        }
                      })
                    ],
                  ),
                ),
              ),
            ),
          ),
        );

  showAlertDialog(BuildContext context) {
    // set up the buttons
    Widget cancelButton = TextButton(
      child: const Text("Permancer"),
      onPressed: () {
        Navigator.of(context).pop(); // dismiss dialog
      },
    );
    Widget continueButton = TextButton(
      child: const Text("Cerrar Sesion"),
      onPressed: () {
        Navigator.push(
          context,
          MaterialPageRoute(
            builder: (context) {
              return logIn();
            },
          ),
        );
      },
    );

    // set up the AlertDialog
    AlertDialog alert = AlertDialog(
      title: const Text("AMMVEE"),
      content: const Text("Quieres cerrar sesion?"),
      actions: [
        cancelButton,
        continueButton,
      ],
    );

    // show the dialog
    showDialog(
      context: context,
      builder: (BuildContext context) {
        return alert;
      },
    );
  }
}
